export const baseUrl = "https://api.themoviedb.org/3/";
export const API_TOKEN =
	"eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzODEzMTllYWVjZjUyMjU4YjI4ZDY3MWE0NjQzYTIzNiIsInN1YiI6IjY1NGJjNGVhMjg2NmZhMDBmZTAxYjMxNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ._h5PkIUYfbfD-bA_miksXaxjsUKNaFEzm5cNAU5FjVw";
